import React, { createContext, useContext, useMemo, useState } from "react";

const translations = {
  pt: { nav: ["PROJETOS", "SOBRE", "LAB", "CONTATO"], heroKicker: "PORTFÓLIO · 2024", heroTitle: <>Design que<br /><em>conta histórias.</em></>, heroText: "Maria Júlia Aquatti é designer focada em criar experiências visuais que unem estratégia, estética e tecnologia.", viewProjects: "VER PROJETOS", available: <>DISPONÍVEL PARA<br />NOVOS PROJETOS</>, projects: "PROJETOS", featured: <>trabalhos<br />em <em>destaque.</em></>, allProjects: "VER TODOS OS PROJETOS", caseKicker: "UI/UX · MOBILE APP", liveProject: "VER PROJETO AO VIVO", about: "SOBRE MIM", aboutTitle: <>Design é onde<br /><em>ideias ganham forma.</em></>, aboutText: ["Sou Maria Júlia, designer com experiência em UI/UX, direção de arte e design digital. Meu trabalho nasce do encontro entre estratégia, estética e tecnologia.", "Gosto de transformar problemas complexos em experiências claras, bonitas e memoráveis — da primeira ideia até a execução."], lab: "LAB", labTitle: <>experiments<br /><em>& side projects.</em></>, labText: <>Onde a interface<br />vira experiência.</>, contact: "VAMOS CONVERSAR?", contactTitle: <>Tem um projeto<br />em <em>mente?</em></>, openCase: "ABRIR CASE COMPLETO" },
  en: { nav: ["WORK", "ABOUT", "LAB", "CONTACT"], heroKicker: "PORTFOLIO · 2024", heroTitle: <>Design that<br /><em>tells stories.</em></>, heroText: "Maria Júlia Aquatti is a designer creating visual experiences that bring strategy, aesthetics, and technology together.", viewProjects: "VIEW PROJECTS", available: <>AVAILABLE FOR<br />NEW PROJECTS</>, projects: "PROJECTS", featured: <>selected<br /><em>work.</em></>, allProjects: "VIEW ALL PROJECTS", caseKicker: "UI/UX · MOBILE APP", liveProject: "VIEW LIVE PROJECT", about: "ABOUT ME", aboutTitle: <>Design is where<br /><em>ideas take shape.</em></>, aboutText: ["I am Maria Júlia, a designer with experience in UI/UX, art direction, and digital design. My work is born where strategy, aesthetics, and technology meet.", "I enjoy turning complex problems into clear, beautiful, and memorable experiences — from the first idea to execution."], lab: "LAB", labTitle: <>experiments<br /><em>& side projects.</em></>, labText: <>Where interfaces<br />become experiences.</>, contact: "LET'S TALK?", contactTitle: <>Have a project<br />in <em>mind?</em></>, openCase: "OPEN FULL CASE" },
  fr: { nav: ["PROJETS", "À PROPOS", "LAB", "CONTACT"], heroKicker: "PORTFOLIO · 2024", heroTitle: <>Le design qui<br /><em>raconte des histoires.</em></>, heroText: "Maria Júlia Aquatti est designer et crée des expériences visuelles qui unissent stratégie, esthétique et technologie.", viewProjects: "VOIR LES PROJETS", available: <>DISPONIBLE POUR<br />DE NOUVEAUX PROJETS</>, projects: "PROJETS", featured: <>travaux<br /><em>sélectionnés.</em></>, allProjects: "VOIR TOUS LES PROJETS", caseKicker: "UI/UX · APPLICATION MOBILE", liveProject: "VOIR LE PROJET", about: "À PROPOS", aboutTitle: <>Le design est l'endroit où<br /><em>les idées prennent forme.</em></>, aboutText: ["Je suis Maria Júlia, designer avec de l'expérience en UI/UX, direction artistique et design numérique. Mon travail naît de la rencontre entre stratégie, esthétique et technologie.", "J'aime transformer les problèmes complexes en expériences claires, belles et mémorables — de la première idée à la réalisation."], lab: "LAB", labTitle: <>expériences<br /><em>& projets personnels.</em></>, labText: <>Là où l'interface<br />devient expérience.</>, contact: "PARLONS-EN ?", contactTitle: <>Vous avez un projet<br />en <em>tête ?</em></>, openCase: "OUVRIR L'ÉTUDE COMPLÈTE" },
};

const LanguageContext = createContext();
export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("pt");
  const value = useMemo(() => ({ language, setLanguage, t: translations[language] }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
export function useLanguage() { return useContext(LanguageContext); }
